# Generated by Django 5.2.3 on 2025-06-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('form', 'Форма')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
