# Generated by Django 5.2.3 on 2025-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Является шаблоном'),
        ),
    ]
