# Generated by Django 5.2.3 on 2025-06-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioelement',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='scenarioelement',
            name='action_type',
            field=models.CharField(choices=[('form', 'Форма'), ('form', 'Меню')], max_length=20),
        ),
    ]
