# Generated by Django 5.2.3 on 2025-06-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_scenarioelement_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioelement',
            name='action_type',
            field=models.CharField(choices=[('form', 'Форма'), ('menu', 'Меню')], max_length=20),
        ),
    ]
