# Generated by Django 5.2.3 on 2025-06-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_alter_scenarioelement_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioelement',
            name='action_type',
            field=models.CharField(choices=[('form', 'Форма'), ('menu', 'Меню'), ('break', 'Выход из диалога')], max_length=20),
        ),
    ]
