# Generated by Django 5.2.3 on 2025-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_remove_scenarioelement_owner_scenario_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='graph',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
