# Generated by Django 5.2.3 on 2025-06-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('menu', '0004_remove_menufield_menu_and_more'),
        ('scenarios', '0007_scenario_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScenarioElement',
        ),
    ]
