version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
    ports:
      - "5432:5432"

  web:
    image: 'web'
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web_migrate

  web_migrate:
    image: web:latest
    command: python manage.py migrate
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./web_app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: