# Generated by Django 5.2.3 on 2025-09-14 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('value', models.TextField(verbose_name='Field Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='chats.chat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'unique_together': {('name', 'chat')},
            },
        ),
    ]
