# Generated by Django 5.2.3 on 2025-06-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='scenarios.scenario'),
        ),
    ]
