# Generated by Django 5.2.3 on 2025-06-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('scenario_element_link', 'Ссылка на элемент сценарий'), ('exit', 'Выход')], max_length=55)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='menu.menu')),
            ],
        ),
    ]
