# Generated by Django 5.2.3 on 2025-06-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('scenarios', '0002_scenarioelement_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufield',
            name='linked_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.scenarioelement'),
        ),
    ]
