# Generated by Django 5.2.3 on 2025-06-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menufield_linked_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufield',
            name='show_condition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
