# Generated by Django 5.2.3 on 2025-06-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='final_message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
