# Generated by Django 5.2.3 on 2025-06-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_final_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
